### ISSUE TITLE
Non-standalone files still point to kubernetesjsonschema.dev

### ISSUE THREAD

**Issue by danielhoherd** [yannh/kubernetes-json-schema#4]
The original project that this was forked from is backed by netlify. Because of that, many of the links that have been updated in this repo are pointing to 404 URls. EG: <https://github.com/yannh/kubernetes-json-schema/blob/ac780627b40b/v1.21.1/all.json#L4>

I suggest we modify the project to publish to GH Pages instead of netlify, so any fork can publish to its own domain without having any one fork break the rest by its going stale like the parent project did.

This fork is by far the most active, so I am opening this issue here.

**Comment by yannh** [comment]
Hi @danielhoherd , there is no need to publish this to Netlify, Github serves this pretty well already...  However all those links are wrong indeed, and I never noticed since I personally use the "standalone" ones. I ve updated the title of this bug and will fix this asap.

**Comment by yannh** [comment]
@danielhoherd I have just committed a fix for all references. If you could validate that this works for you :pray: Thanks!

**Comment by danielhoherd** [comment]
Currently it's still failing with the following error:
```
  E           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.14.0/serviceaccount-v1.json
838
```
But this might be due to our configurations that need to be updated. We'll get back to you about it.

Thanks for the quick update!

**Comment by yannh** [comment]
1.14 has been EOL for a while.. this repo doesn't have those schemas anymore, only 1.15+...

**Comment by danielhoherd** [comment]
Oh yeah, good call on 1.14. I have an issue open on our side that mentions moving off this deprecated version.
